### ISSUE TITLE
windows prebuild & build error(vs2017)

### ISSUE THREAD

**Issue by thewaterislo** [lailongwei/llbc#288]
/llbc/tools/premake/premake5.lua:101: Unsupported architecture, for now, llbc framework supported systems: x86/ARM

**Comment by thewaterislo** [comment]
我用的windows，怎么报错是不支持的系统架构？

**Comment by lailongwei** [comment]
@thewaterislo  @这边看了下[premake5.lua:101](https://github.com/lailongwei/llbc/blob/master/tools/premake/premake5.lua)，理论上不会出现这个**不支持的architecture**报错，可以提供更详细的信息吗？
![image](https://github.com/user-attachments/assets/158086e5-02cf-4e22-b948-e796d58e020f)

**Comment by lailongwei** [comment]
qq群：662590231，可以进这个群讨论问题，较方便

**Comment by thewaterislo** [comment]
![1731481240506](https://github.com/user-attachments/assets/4fad207f-1386-4670-a1b1-71e4bf6c877e)
原因如图，‘uname -m’是linux环境命令，就是需要windows安装msys2，cygwin之类的环境了？

**Comment by lailongwei** [comment]
> Author

看到`WinPreBuild.bat`脚本已经有很多报错，我这边也试着用vs2017试一下，当前llbc要求`c++17`版本，但也只用了部分特性，当前`github actions`中没有跑`vs2017`的action，可能会有一些编译问题
![image](https://github.com/user-attachments/assets/5688df59-5e8e-44d2-8438-795400cc232a)

**Comment by lailongwei** [comment]
> ![1731481240506](https://private-user-images.githubusercontent.com/67196618/385632970-4fad207f-1386-4670-a1b1-71e4bf6c877e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODM0OTIsIm5iZiI6MTczMTQ4MzE5MiwicGF0aCI6Ii82NzE5NjYxOC8zODU2MzI5NzAtNGZhZDIwN2YtMTM4Ni00NjcwLWExYjEtNzFlNGJmNmM4NzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA3MzMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZWE0ZjYwZmRlOWY2NmQwMDE3YTUyYzlkYjZkMzYzY2M0NDI2M2E3YjgyNjE0MTEwNGM4NGQ1YTBmNDJhMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mRgA6LVyJB4B3QYlplNMiUrmlx_d3C9LRv5nYCq9H1Q) 原因如图，‘uname -m’是linux环境命令，就是需要windows安装msys2，cygwin之类的环境了？

可以在premake5.lua:63行加如下代码吗？打印一下`premake`内部变量`_ACTION`，怀疑这里出了问题，llbc不要求任何`msys2`、`cygwin`这类`linux模拟环境`的

```lua
print(string.format('The _ACTION is %s', _ACTION))
```

**Comment by lailongwei** [comment]
> > ![1731481240506](https://private-user-images.githubusercontent.com/67196618/385632970-4fad207f-1386-4670-a1b1-71e4bf6c877e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODM0OTIsIm5iZiI6MTczMTQ4MzE5MiwicGF0aCI6Ii82NzE5NjYxOC8zODU2MzI5NzAtNGZhZDIwN2YtMTM4Ni00NjcwLWExYjEtNzFlNGJmNmM4NzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA3MzMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZWE0ZjYwZmRlOWY2NmQwMDE3YTUyYzlkYjZkMzYzY2M0NDI2M2E3YjgyNjE0MTEwNGM4NGQ1YTBmNDJhMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mRgA6LVyJB4B3QYlplNMiUrmlx_d3C9LRv5nYCq9H1Q) 原因如图，‘uname -m’是linux环境命令，就是需要windows安装msys2，cygwin之类的环境了？
> 
> 可以在premake5.lua:63行加如下代码吗？打印一下`premake`内部变量`_ACTION`，怀疑这里出了问题，llbc不要求任何`msys2`、`cygwin`这类`linux模拟环境`的
> 
> ```lua
> print(string.format('The _ACTION is %s', _ACTION))
> ```

这个是这边输出的结果：
![image](https://github.com/user-attachments/assets/c401a627-87d2-4191-9999-df4b38e89a36)

**Comment by thewaterislo** [comment]
我对premake并不了解，需要我装premake吗？类似cmake的

**Comment by lailongwei** [comment]
> 我对premake并不了解，需要我装premake吗？类似cmake的

不需要的哈，`premake`是一个非常精简的`pre-build`系统，llbc内部直接将其bin带进去了的，我这边再看一下，这个问题第一次遇到，稍等哈

**Comment by lailongwei** [comment]
> 我对premake并不了解，需要我装premake吗？类似cmake的

![image](https://github.com/user-attachments/assets/25ec3355-73e0-4118-9de1-ecb3ea5fb3b1)

**Comment by thewaterislo** [comment]
![1731484348768](https://github.com/user-attachments/assets/2a56e1c3-0f73-4979-b4bc-3ec9480bf2e6)

**Comment by lailongwei** [comment]
> ![1731484348768](https://private-user-images.githubusercontent.com/67196618/385648874-2a56e1c3-0f73-4979-b4bc-3ec9480bf2e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODQ2NzAsIm5iZiI6MTczMTQ4NDM3MCwicGF0aCI6Ii82NzE5NjYxOC8zODU2NDg4NzQtMmE1NmUxYzMtMGY3My00OTc5LWI0YmMtM2VjOTQ4MGJmMmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA3NTI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MTA4ZjYyZTNhZWY5YjE1YTRhZjU0YzY4OGM1MDg1YjE2MjI2YTczOThhOTg1ZmI3Y2NmZjMzZTA1M2JjZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Lj_tg0WGOR9T2OEmNUZ-5khZIWNByO4L0z_KzGb-ATU)

找到问题，感谢反馈:)
在`9/26`整理premake脚本时引入的bug，因为这边安装了`git环境`，而git环境又自带了`mingw`环境，所以以下代码就算进去了也能正确得到`arch`是`x86`：
![image](https://github.com/user-attachments/assets/72e3bd71-dabe-4edf-9889-b6d4a8b57fa6)

**Comment by lailongwei** [comment]
@thewaterislo Fixed[c349433](https://github.com/lailongwei/llbc/commit/c3494331d8b2496e5c61d5d3985eb42ef7d5b7a6)，麻烦`pull`，因`vs2017`很久没有测试，如果编译有问题，也麻烦在这个issue中反馈哈，感谢:)

**Comment by thewaterislo** [comment]
我说呢，这个判断not这么奇怪

**Comment by lailongwei** [comment]
> 我说呢，这个判断not这么奇怪

@thewaterislo 哈哈，手抖，应该是9月份支持`arm`芯片的`mac`时引入

**Comment by lailongwei** [comment]
@thewaterislo 编译时，麻烦注意vs的**解决方案-架构**选择，需要对应，不要选择`release64`后，架构又选择`x86`，编译会直接失败：
![image](https://github.com/user-attachments/assets/e4dab0f5-f067-40d4-8d80-13ae54f16a10)

**Comment by thewaterislo** [comment]
![1731547381847](https://github.com/user-attachments/assets/b7443799-f033-433f-8356-56eaf43a995e)
![1731547914103](https://github.com/user-attachments/assets/d53f369d-93bf-4f6c-8f1c-dea8e0cb7a1a)
首先，前面两个报错，这两个函数在我vs2017里是全局的，并不在std里；其次第三个报错显示是已经删除的函数；我编译选择的win10SDK是10.0.17763.0，默认的8.1会有很多头文件找不到

**Comment by lailongwei** [comment]
> ![1731547381847](https://private-user-images.githubusercontent.com/67196618/386001659-b7443799-f033-433f-8356-56eaf43a995e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NDgzODYsIm5iZiI6MTczMTU0ODA4NiwicGF0aCI6Ii82NzE5NjYxOC8zODYwMDE2NTktYjc0NDM3OTktZjAzMy00MzNmLTgzNTYtNTZlYWY0M2E5OTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDAxMzQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTQ3NTg3YWQ3NmUwMjAxNjk1ZTNhYjVjYmRiZWYxNTY4ZTk0NmYyYWZmN2VkZDdiZDFiZmYwZTUxZTVjZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CHON2d5ack_v8CaBDZBfDUfu7dICJ6hMBo6-k90vGvE) ![1731547914103](https://private-user-images.githubusercontent.com/67196618/386003066-d53f369d-93bf-4f6c-8f1c-dea8e0cb7a1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NDgzODYsIm5iZiI6MTczMTU0ODA4NiwicGF0aCI6Ii82NzE5NjYxOC8zODYwMDMwNjYtZDUzZjM2OWQtOTNiZi00ZjZjLThmMWMtZGVhOGUwY2I3YTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDAxMzQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZDg4MDYwMjU0ZTkxZjk1YTA5YWQ5ZjEwOTM2OTcyOTNiZWVjMGRlOTg4MzRiNzk2NWUxOWJjZGNmMTUwY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6d71n9M5GBSbKIn1OJGrYCwnyOb-PM5ekfk5u4eElf4) 首先，前面两个报错，这两个函数在我vs2017里是全局的，并不在std里；其次第三个报错显示是已经删除的函数；我编译选择的win10SDK是10.0.17763.0，默认的8.1会有很多头文件找不到

`std::isdigit`、`std::isalpha`在`<cctype>`中定义，但在[cppreference](https://en.cppreference.com/w/cpp/string/byte/isdigit)中没找到实际引入的时间，这个很基础的函数，应该较早前就引入，而llbc在Properties.cpp中没有显式包含，也没在OSHeader.h中包含，这边建议：**在Properties.cpp**的`#include "llbc/common/Export.h"后面进行包含，然后尝试只编译这个文件(`Ctrl + F7`)`看是否能解决

另外一个**Variant转std::pair问题**，llbc中是有实现的：
```c++
template <typename _T1, typename _T2>
LLBC_Variant::operator std::pair<_T1, _T2>() const
{
    if (!IsSeq() || Size() < 2)
        return std::make_pair(_T1(), _T2());

    const Seq &seq = *_holder.data.obj.seq;
    return std::make_pair<_T1, _T2>(seq[0], seq[1]);
}
```
当前怀疑是编译器过老导致的问题，可以麻烦这样修改：
方案一：将报错的文件`TestCase_Core_Variant.cpp`的那一行修改为显式case，看是否能通过
```c++
    pa = static_cast<std::pair<std::vector<int>, std::map<int, int> > >(var2);
```

**Comment by lailongwei** [comment]
`Visual Studio`版本支持这块，这边最近会抽时间确认**最低支持的Visual Studio版本**，尽量确保Visual Studio 2017版本可支持 @thewaterislo

**Comment by lailongwei** [comment]
@thewaterislo 发现这边有vs2017的版本，我也试一下，安装需要一会

**Comment by thewaterislo** [comment]
@lailongwei 厉害，按照你的方法可以，现在32,64，debug，release都行了

**Comment by lailongwei** [comment]
> @lailongwei 厉害，按照你的方法可以，现在32,64，debug，release都行了

可以的话，麻烦提交一个pull request过来哈，这边也就不尝试啦，感谢感谢

**Comment by lailongwei** [comment]
@thewaterislo llbc目前几乎没有文档，有任何使用问题（包括可以用来做什么 跟 建议的使用范式 这些），还麻烦直接进qq群：662590231 交流哈，截图一个我们当前项目的app使用示例（隐去敏感信息）：
![image](https://github.com/user-attachments/assets/0b91ecb3-90c4-4aba-a081-e4b1bc129182)

**Comment by thewaterislo** [comment]
额，我还没有pull request过，我研究下
