### ISSUE TITLE
Log建议增加一个开关，初始化时不要创建空的logger文件，只有第一次输出时才创建

### ISSUE THREAD

**Issue by zhouyanlt** [lailongwei/llbc#4]
RT

**Comment by lailongwei** [comment]
此功能增加，增加这个开关不是非常复杂，你有空的时候，可以自己添加一下，另外这个需求，也会录入到llbc项目todo中 @zhouyanlt

**Comment by lailongwei** [comment]
@zhouyanlt 忆看到@WayToGn创建了pull request，但有一处代码风格不符合llbc框架规范，再作一次提交即可，此issue关闭
