### ISSUE TITLE
llbc-python3编译失败

### ISSUE THREAD

**Issue by 3638836363** [lailongwei/llbc#66]
[root@ysz llbc]# make py_wrap
Python 2.6.6
Building configurations...
Running action 'gmake'...
Done (2080ms).
make[1]: Entering directory `/home/llbc/build/gmake'
make[1]: Leaving directory `/home/llbc/build/gmake'
make[1]: Entering directory `/home/llbc/build/gmake'
Running prebuild commands
python ../../tools/building_script/py_prebuild.py pyllbc
Build methods... Done
Build script integrator... Done
Application.cpp
In file included from ../../wrap/pyllbc/include/pyllbc/common/ObjAttrOptr.h:76:0,
                 from ../../wrap/pyllbc/include/pyllbc/common/Common.h:33,
                 from ../../wrap/pyllbc/include/pyllbc/application/PyApplication.h:25,
                 from ../../wrap/pyllbc/src/application/Application.cpp:24:
../../wrap/pyllbc/include/pyllbc/common/ObjAttrOptrImpl.h: In member function ‘int pyllbc_ObjAttrOptr::SetAttr(const LLBC_String&, const _Val&) [with _Val = llbc::LLBC_BasicString<char>; llbc::LLBC_String = llbc::LLBC_BasicString<char>]’:
../../wrap/pyllbc/include/pyllbc/common/ObjAttrOptrImpl.h:300:71: error: ‘PyString_FromStringAndSize’ was not declared in this scope
     PyObject *oVal = PyString_FromStringAndSize(val.data(), val.size());
                                                                       ^
../../wrap/pyllbc/include/pyllbc/common/ObjAttrOptrImpl.h: In member function ‘int pyllbc_ObjAttrOptr::SetAttr(const LLBC_String&, const _Val&) [with _Val = char*; llbc::LLBC_String = llbc::LLBC_BasicString<char>]’:
../../wrap/pyllbc/include/pyllbc/common/ObjAttrOptrImpl.h:311:45: error: ‘PyString_FromString’ was not declared in this scope
     PyObject *oVal = PyString_FromString(val);
                                             ^
../../wrap/pyllbc/include/pyllbc/common/ObjAttrOptrImpl.h: In member function ‘int pyllbc_ObjAttrOptr::SetAttr(const LLBC_String&, const _Val&) [with _Val = long int; llbc::LLBC_String = llbc::LLBC_BasicString<char>]’:
../../wrap/pyllbc/include/pyllbc/common/ObjAttrOptrImpl.h:344:40: error: ‘PyInt_FromLong’ was not declared in this scope
     PyObject *oVal = PyInt_FromLong(val);

**Comment by lailongwei** [comment]
@3638836363 Hi，你好，pyllbc为完整的库，当前因为时间关系，未完整提供py3支持，将会在12月底前完成支持，py2的支持是完整且经过上线产品验证的，可以先使用。
如果您这边有空的话，也可以协助进行py3支持工作哈，我们的QQ群：662590231

**Comment by 3638836363** [comment]
申请了几天了 ~.

**Comment by lailongwei** [comment]
@3638836363 抱歉，已经同意哈
