### ISSUE TITLE
Mac 平台上make core_lib编译无法成功

### ISSUE THREAD

**Issue by WayToGn** [lailongwei/llbc#8]
Mac平台上make core_lib 编译不通过
![image](https://user-images.githubusercontent.com/20799650/38793779-2ccd43f8-4185-11e8-9b8a-be144796aa05.png)

**Comment by lailongwei** [comment]
llbc最近调整非常大，因为时间关系，未集成CI及在其它平台编译验证，还麻烦你看一下问题，并进行修复 @WayToGn

**Comment by lailongwei** [comment]
应该是非常小的问题

**Comment by WayToGn** [comment]
OK

**Comment by WayToGn** [comment]
linux 平台编译可以通过吗？

**Comment by lailongwei** [comment]
应该只有windows可以编译通过，看你的截图，应该是一个函数调用适配的问题，简单找一下，应该能定位到
